name: Prepare

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_versions:
    name: Check versions
    runs-on: ubuntu-latest
    outputs:
      react_version: ${{ steps.react_version.outputs.current-version }}
      check_react_version: ${{ steps.check_react_version.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Get React version
        id: react_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/@pbcomponents-react

      - name: Check React version
        id: check_react_version
        uses: EndBug/version-check@v2
        with:
          file-name: ./packages/@pbcomponents-react/package.json
          file-url: https://unpkg.com/@pbcomponents/react@latest/package.json
          static-checking: localIsNew

  create_react_tag:
    name: Create React tag
    if: needs.check_versions.outputs.check_react_version == 'true'
    needs: [check_versions]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "REACT_TAG_NAME=@pbcomponents/react@v${{ needs.check_versions.outputs.react_version }}" >> $GITHUB_ENV
      - uses: joutvhu/create-tag@v1
        with:
          tag_name: ${{ env.REACT_TAG_NAME }}
          message: ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
