name: Release

on:
  push:
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write

env:
  NODE_VERSION: 22.x

jobs:
  publish:
    name: Build and publish library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci --legacy-peer-deps

      - name: Check React
        if: startsWith(github.ref, 'refs/tags/@pbcomponents/react')
        run: |
          echo "FRAMEWORK=react" >> $GITHUB_ENV
          echo "PACKAGE_PATH=./packages/@pbcomponents-react" >> $GITHUB_ENV

      - run: npm run build:${{ env.FRAMEWORK }}
      - run: npm publish ${{ env.PACKAGE_PATH }} --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create_release:
    name: Create release
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          draft: false
          prerelease: false
          make_latest: true

  call_react_vercel_webhook:
    name: Call React Vercel webhook
    if: startsWith(github.ref, 'refs/tags/@pbcomponents/react')
    runs-on: ubuntu-latest
    needs: [create_release]
    steps:
      - uses: actions/checkout@v4
      - uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.REACT_VERCEL_WEBHOOK_URL }}
