name: Release

on:
  release:
    types: [prereleased]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_VERSION: 18.x

jobs:
  build:
    name: Build and publish library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci

      - name: Check React
        if: startsWith(github.ref, 'refs/tags/@pbcomponents/react')
        run: |
          echo "FRAMEWORK=react" >> $GITHUB_ENV
          echo "PACKAGE_PATH=./packages/@pbcomponents-react" >> $GITHUB_ENV

      - name: Check Vue
        if: startsWith(github.ref, 'refs/tags/@pbcomponents/vue')
        run: |
          echo "FRAMEWORK=vue" >> $GITHUB_ENV
          echo "PACKAGE_PATH=./packages/@pbcomponents-vue" >> $GITHUB_ENV

      - run: npm run build:${{ env.FRAMEWORK }}
      - run: npm publish ${{ env.PACKAGE_PATH }} --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update_release:
    name: Update release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false

  call_react_vercel_webhook:
    name: Call React Vercel webhook
    if: startsWith(github.ref, 'refs/tags/@pbcomponents/react')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.REACT_VERCEL_WEBHOOK_URL }}

  call_vue_vercel_webhook:
    name: Call Vue Vercel webhook
    if: startsWith(github.ref, 'refs/tags/@pbcomponents/vue')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.VUE_VERCEL_WEBHOOK_URL }}
